language: java
jdk:
  - openjdk8

branches:
  only:
    - master

#Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알림
notifications:
  email:
    recipients:
      - tries1@naver.com

before_deploy:
  - zip -r spring-aws-sample-was *
  - mkdir -p deploy
  - mv spring-aws-sample-was.zip deploy/spring-aws-sample-was

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # at travis config setting
    secret_access_key: $AWS_SECRET_KEY # at travis config setting

    bucket: spring-aws-sample-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # at travis config setting
    secret_access_key: $AWS_SECRET_KEY # at travis config setting

    bucket: spring-aws-sample-build
    key: spring-aws-sample-was
    bundle_type: zip
    application: spring-aws-was
    deployment_group: spring-aws-group
    region: ap-northeast-2
    wait-until-deployed: true