server:
  port: 8082

spring:
  profiles.include: oauth,real-db
  jpa:
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  session:
    store-type: jdbc